seed: 42
data:
  data_dir: "./data/WMT14EnDe"
  max_length: 128
  batch_size: 64
  num_workers: 8
model:
  num_layers: 6
  d_model: 512
  num_heads: 8
  d_ff: 2048
  dropout_p: 0.1
train:
  lr: 1e-3
  epochs: 100
  warmup_ratio: 0.1
  patience: 2
email:
  to: "yumemonzo@gmail.com"
  from: "yumemonzo@gmail.com"
  password: "gbnl jjqb uetw oahk"